name: almeidatec
description: "Desafio Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  web: true
  windows: true
  image_path: "assets/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#994EFE"  
  image: assets/splash_logo.png 
  android: true
  ios: true
  web: true
  fullscreen: true
