name: almeidatec
description: "Desafio Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.2.2
  awidgets:
    git:
      url: https://gitlab.com/almeidatech/awidgets.git
      ref: main
      
  firebase_core: ^2.32.0
  firebase_messaging: ^14.8.0
  js: ^0.6.3
  excel: ^2.0.6

  file_picker: ^6.1.1
  
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  extended_masked_text: ^3.0.1

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.3.3

  flutter_native_splash: ^2.4.4
  flutter_secure_storage: ^10.0.0-beta.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

  freezed: ^2.5.7
  build_runner: ^2.4.9
  json_serializable: ^6.0.0
  
flutter_icons:
  android: true
  ios: true
  web: true
  windows: true
  image_path: "assets/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#994EFE"  
  image: assets/splash_logo.png 
  android: true
  ios: true
  web: true
  fullscreen: true


